---
- name: Generate Jenkins API Token
  hosts: all
  remote_user: "{{ lookup('env', 'REMOTE_USER') }}"
  gather_facts: false


  tasks:
    - name: Set environmental variables
      ansible.builtin.set_fact:
        jenkins_password: "{{ lookup('env', 'JENKINS_PASSWORD') }}"
        jenkins_user: "admin"
        jenkins_url: "http://localhost:8085"
        github_token: "{{ lookup('env', 'GH_KEY') }}"
        webhook_url: "{{ lookup('env', 'WEBHOOK_URL') }}"

    - name: Get Jenkins Crumb
      uri:
        url: "{{ jenkins_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"
        method: GET
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        force_basic_auth: true
        return_content: true
      register: crumb

    - name: Generate Jenkins API Token
      uri:
        url: "{{ jenkins_url }}/user/{{ jenkins_user }}/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken"
        method: POST
        follow_redirects: all
        force_basic_auth: true
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        body_format: json
        headers:
          Content-Type: "application/json"
          Cookie: '{{ crumb.set_cookie }}'
          Jenkins-Crumb: "{{ crumb.content.split(':')[1]}}"
        return_content: true
      register: token_result


    - name: Add GitHub Webhook
      uri:
        url: "https://api.github.com/repos/patry77/spring-petclinic/hooks"
        method: POST
        headers:
          Accept: "application/vnd.github+json"
          Authorization: "Bearer {{ github_token }}"
        body_format: json
        body:
          name: "Jenkins pipeline"
          active: true
          events:
            - "push"
          config:
            url: "http://{{ webhook_url }}/github-webhook/"
            content_type: "json"
            insecure_ssl: "1"
            secret: "{{ token_result.json.data.tokenValue }}"
        status_code: 201
      register: result
