---
- name: Configure Nexus
  hosts: pipelinevm
  remote_user: "{{ vm_user }}"
  become: yes
  tasks:
  
      - name: Update APT
        apt:
          update_cache: yes
        when: ansible_os_family == 'Debian'
        
      - name: Install Java OpenJDK
        apt:
          name: openjdk-17-jdk
        when: ansible_os_family == 'Debian'

      - name: Install Docker
        apt:
          name: docker.io
          state: present
        when: ansible_os_family == "Debian"

      - name: Install python-docker
        pip:
          name: docker