---
- name: Generate Jenkins API Token
  hosts: all
  remote_user: "{{ lookup('env', 'REMOTE_USER') }}"
  gather_facts: false


  tasks:
    - name: Set Jenkins password
      ansible.builtin.set_fact:
        jenkins_password: "{{ lookup('env', 'JENKINS_PASSWORD') }}"
        jenkins_user: "admin"
        jenkins_url: "http://localhost:8085"

    - name: Get Jenkins Crumb
      uri:
        url: "{{ jenkins_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"
        method: GET
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        force_basic_auth: true
        return_content: true
      register: crumb

    - name: Generate Jenkins API Token
      uri:
        url: "{{ jenkins_url }}/user/{{ jenkins_user }}/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken"
        method: POST
        follow_redirects: all
        force_basic_auth: true
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        body_format: json
        headers:
          Content-Type: "application/json"
          Cookie: '{{ crumb.set_cookie }}'
          Jenkins-Crumb: "{{ crumb.content.split(':')[1]}}"
        return_content: true
      register: token_result

    - debug:
        var: token_result