---
- name: Configure jenkins
  hosts: pipelinevm
  remote_user: "{{ vm_user }}"
  become: yes

  tasks:
    - name: Include encrypted variables
      include_vars: vault/credentials.yml

    - name: Install Jenkins plugins
      community.general.jenkins_plugin:
        name: "{{ item }}"
        url_username: "admin"
        url_password: "{{ jenkins_password }}"
        url: http://localhost:8085
        timeout: 120
        state: latest
      with_items:  
        - ace-editor
        - ant
        - antisamy-markup-formatter
        - apache-httpcomponents-client-4-api
        - bootstrap4-api
        - bootstrap5-api
        - bouncycastle-api
        - branch-api
        - build-timeout
        - caffeine-api
        - checks-api
        - cloudbees-folder
        - command-launcher
        - credentials
        - credentials-binding
        - display-url-api
        - durable-task
        - echarts-api
        - email-ext
        - font-awesome-api
        - git
        - git-client
        - git-server
        - github
        - github-api
        - github-branch-source
        - gradle
        - handlebars
        - jackson2-api
        - jaxb
        - jdk-tool
        - jjwt-api
        - jquery3-api
        - jsch
        - junit
        - ldap
        - lockable-resources
        - mailer
        - matrix-auth
        - matrix-project
        - momentjs
        - okhttp-api
        - pam-auth
        - pipeline-build-step
        - pipeline-github-lib
        - pipeline-graph-analysis
        - pipeline-input-step
        - pipeline-milestone-step
        - pipeline-model-api
        - pipeline-model-definition
        - pipeline-model-extensions
        - pipeline-rest-api
        - pipeline-stage-step
        - pipeline-stage-tags-metadata
        - pipeline-stage-view
        - plain-credentials
        - plugin-util-api
        - popper-api
        - popper2-api
        - resource-disposer
        - scm-api
        - script-security
        - snakeyaml-api
        - ssh-credentials
        - ssh-slaves
        - sshd
        - structs
        - timestamper
        - token-macro
        - trilead-api
        - workflow-aggregator
        - workflow-api
        - workflow-basic-steps
        - workflow-cps
        - workflow-cps-global-lib
        - workflow-durable-task-step
        - workflow-job
        - workflow-multibranch
        - workflow-scm-step
        - workflow-step-api
        - workflow-support
        - ws-cleanup
   
    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted

    - name: Configure Jenkins Job with Jenkinsfile
      shell: |
          java -jar /home/patry/jenkins-cli.jar -s http://localhost:8085/ -auth admin:{{ jenkins_password }} groovy = <<EOF
          import jenkins.model.Jenkins
          def jenkins = Jenkins.instance
          import hudson.plugins.git.*;

          def scm = new GitSCM("https://github.com/patry77/spring-petclinic.git")
          scm.branches = [new BranchSpec("*/main")];

          def flowDefinition = new org.jenkinsci.plugins.workflow.cps.CpsScmFlowDefinition(scm, "Jenkinsfile")

          def parent = Jenkins.instance
          def job = new org.jenkinsci.plugins.workflow.job.WorkflowJob(parent, "spring-petclinic")
          job.definition = flowDefinition

          parent.reload()
          EOF
      args:
        executable: /bin/bash
      ignore_errors: true
    - name: Add Jenkins credentials
      shell: |
          java -jar /home/patry/jenkins-cli.jar -s http://localhost:8085/ -auth admin:{{ jenkis_password }} groovy = <<EOF
          import com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl
          import com.cloudbees.plugins.credentials.*

          def creds = new UsernamePasswordCredentialsImpl(
              CredentialsScope.GLOBAL,
              "githubToken",
              "GitHub Token",
              "patry77",
              "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"
          )

          SystemCredentialsProvider.getInstance().getCredentials().add(creds)
          SystemCredentialsProvider.getInstance().save()
          EOF