---
- name: Generate Jenkins API Token
  hosts: all
  remote_user: "{{ lookup('env', 'REMOTE_USER') }}"
  gather_facts: false


  tasks:
    - name: Set environmental variables
      ansible.builtin.set_fact:
        jenkins_password: "{{ lookup('env', 'JENKINS_PASSWORD') }}"
        jenkins_user: "admin"
        jenkins_url: "http://localhost:8085"
        github_token: "{{ lookup('env', 'GH_KEY') }}"
        webhook_url: "{{ lookup('env', 'WEBHOOK_URL') }}"

    - name: Get Jenkins Crumb
      uri:
        url: "{{ jenkins_url }}/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"
        method: GET
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        force_basic_auth: true
        return_content: true
      register: crumb

    - name: Generate Jenkins API Token
      uri:
        url: "{{ jenkins_url }}/user/{{ jenkins_user }}/descriptorByName/jenkins.security.ApiTokenProperty/generateNewToken"
        method: POST
        follow_redirects: all
        force_basic_auth: true
        user: "{{ jenkins_user }}"
        password: "{{ jenkins_password }}"
        body_format: json
        headers:
          Content-Type: "application/json"
          Cookie: '{{ crumb.set_cookie }}'
          Jenkins-Crumb: "{{ crumb.content.split(':')[1]}}"
        return_content: true
      register: token_result


    - name: Create a new webhook in a github
      community.general.github_webhook:
        repository: patry77/spring-petclinic
        url: "http://{{ webhook_url }}/github-webhook/"
        content_type: json
        secret: "{{ token_result.json.data.tokenValue }}"
        insecure_ssl: true
        events:
          - push
        user: "patry77"
        token: "{{ github_token: }}"
