---
- name: Configure VM
  hosts: all
  remote_user: "{{ lookup('env', 'REMOTE_USER') }}"
  become: yes
  tasks:
  
      - name: Update APT
        apt:
          update_cache: yes
        when: ansible_os_family == 'Debian'
        
      - name: Install Java OpenJDK
        apt:
          name: openjdk-17-jdk
        when: ansible_os_family == 'Debian'

      - name: Install Docker
        apt:
          name: docker.io
          state: present
        when: ansible_os_family == "Debian"

      - name: Install Python
        apt:
          name: python
          state: present

      - name: Install Pip
        apt:
          name: python3-pip
          state: present

      - name: Install python-docker
        pip:
          name: docker
        ignore_errors: yes

      - name: Install python-github
        pip:
          name: pygithub
        ignore_errors: yes

      - name: Install Snapd
        apt:
          name: snapd
          state: present
        when: ansible_os_family == "Debian"

      - name: Start and enable the Snapd service
        service:
          name: snapd
          state: started
          enabled: yes
        when: ansible_os_family == "Debian"


      - name: Install Google Cloud CLI using Snap
        command: snap install google-cloud-sdk --classic
        ignore_errors: yes
        when: ansible_os_family == "Debian"

      - name: Set GCP Service Account Key
        ansible.builtin.set_fact:
          gcp_service_account_key: "{{ lookup('env', 'gcp_service_account_key') }}"
        when: ansible_os_family == "Debian"

      - name: Copy GCP service account file
        copy:
          content: "{{ gcp_service_account_key }}"
          dest: /home/ubuntu/gcp-service-account.json
        when: ansible_os_family == "Debian"


      - name: Add VM IP to insecure hosts
        shell: |
          echo '{ "insecure-registries": ["{{ lookup('env', 'VM_IP') }}:8082"] }' | sudo tee /etc/docker/daemon.json
