---
- name: Unlock Jenkins
  hosts: all
  remote_user: "{{ lookup('env', 'REMOTE_USER') }}"
  become: yes

  tasks:
    - name: Include encrypted variables
      include_vars: vault/credentials.yml
      
    - name: Copy initial admin password
      command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: admin_password
      changed_when: false

    - name: Download Jenkins CLI
      get_url:
        url: http://localhost:8085/jnlpJars/jenkins-cli.jar
        dest: /home/{{ lookup('env', 'REMOTE_USER') }}/jenkins-cli.jar
        mode: 0755

    - name: Unlock Jenkins
      shell: |
        echo '{{ admin_password.stdout }}' | java -jar /home/{{ lookup('env', 'REMOTE_USER') }}/jenkins-cli.jar -s http://localhost:8085/ -auth admin:{{ admin_password.stdout }} groovy = <<EOF
        import jenkins.model.*
        import hudson.security.*

        def instance = Jenkins.getInstance()
        def hudsonRealm = new HudsonPrivateSecurityRealm(false)
        hudsonRealm.createAccount('admin', '{{ jenkis_password }}')
        def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
        strategy.setAllowAnonymousRead(false)

        instance.setSecurityRealm(hudsonRealm)
        instance.setAuthorizationStrategy(strategy)
        instance.save()
        println "Jenkins is unlocked and configured!"
        EOF
      args:
        executable: /bin/bash
      ignore_errors: true
      
    - name: Jenkins Skip setup
      lineinfile:
        dest=/usr/lib/systemd/system/jenkins.service
        regexp='^Environment="JAVA_OPTS=-Djava.awt.headless=true'
        line='Environment="JAVA_OPTS=-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'

    - name: Restart jenkins
      systemd:
        name: jenkins
        state: restarted
      when: ansible_os_family == 'Debian'