---
- name: Install Nexus
  hosts: 192.168.0.166
  remote_user: patry
  become: yes
  gather_facts: yes
  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present
    when: ansible_os_family == "Debian"

  - name: Start Docker service
    service:
      name: docker
      state: started

  - name: Pull Sonatype Nexus Docker image
    docker_image:
      name: sonatype/nexus3
      source: pull

  - name: Run Sonatype Nexus container
    docker_container:
      name: nexus
      image: sonatype/nexus3
      ports:
        - "8081:8081"
        - "8082:8082"
      state: started