---
- name: Install Nexus
  hosts: 192.168.0.130
  remote_user: patry
  become: yes
  gather_facts: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Java OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present
      when: ansible_os_family == 'Debian'

    - name: Add Nexus repository
      apt_repository:
        repo: deb https://download.sonatype.com/nexus/3/latest/apt {{ ansible_distribution_release }} main
      when: ansible_os_family == 'Debian'

    - name: Install Nexus Repository Manager
      apt:
        name: nexus
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start Nexus service
      service:
        name: nexus
        state: started
        enabled: yes
      when: ansible_os_family == 'Debian'