---
- name: Install Jenkins
  hosts: 192.168.0.130
  remote_user: patry
  become: yes
  gather_facts: yes

  tasks:
    - name: Install Java OpenJDK
      apt:
        name: default-jdk
      when: ansible_os_family == 'Debian'

    - name: Add Jenkins Repository key
      apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
      when: ansible_os_family == 'Debian'

    - name: Add Jenkins repository
      apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present
      when: ansible_os_family == 'Debian'

    - name: Update APT
      apt:
        update_cache: yes
      when: ansible_os_family == 'Debian'

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present
      when: ansible_os_family == 'Debian'

    - name: Start jenkins
      systemd:
        name: jenkins
        enabled: yes
        state: started
      when: ansible_os_family == 'Debian'

    - name: Create Jenkins Workspace Directory
      file:
        path: /var/lib/jenkins/workspace/capstone-project
        state: directory
        mode: '0755'
      when: ansible_os_family == 'Debian'
    
    - name: Download Jenkinsfile
      get_url:
        url: https://raw.githubusercontent.com/patry77/capstone-project/main/ansible/Jenkinsfile
        dest: /var/lib/jenkins/workspace/capstone-project/Jenkinsfile
      when: ansible_os_family == 'Debian'
      

    - name: Restart Jenkins
      service:
        name: jenkins
        state: restarted
      when: ansible_os_family == 'Debian'

