name: Terraform Workflow

on:
  push:
    branches:
      - develop

jobs:
  terraform_loadbalancer:
    name: Terraform Load Balancer
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: Terraform Load Balancer Format
        run: terraform fmt -check -recursive
        working-directory: terraform/loadbalancer

      - name: Terraform Load Balancer Linting
        run: terraform validate
        working-directory: terraform/loadbalancer

      - name: Terraform Load Balancer Init
        run: terraform init
        working-directory: terraform/loadbalancer

      - name: Terraform Load Balancer Plan
        run: terraform plan -input=false -out=tfplan_loadbalancer
        working-directory: terraform/loadbalancer

  terraform_pipelinevm:
    name: Terraform Pipeline VM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.5

      - name: Terraform Pipeline VM Format
        run: terraform fmt -check -recursive
        working-directory: terraform/pipelinevm

      - name: Terraform Pipeline VM Linting
        run: terraform validate
        working-directory: terraform/pipelinevm

      - name: Terraform Pipeline VM Init
        run: terraform init
        working-directory: terraform/pipelinevm

      - name: Terraform Pipeline VM Plan
        run: terraform plan -input=false -out=tfplan_pipelinevm
        working-directory: terraform/pipelinevm
