name: Terraform Pipeline VM Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_CLOUD_TOKEN }}

      - name: Change to Terraform directory
        run: cd terraform/pipelinevm

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Deploy Infrastructure
        run: terraform apply -auto-approve

      - name: Get Outputs
        id: outputs
        run: echo "::set-output name=ip_address::$(terraform output -raw vm_public_ip)"